-- 把 5 张表 id 列改为 GENERATED ALWAYS AS IDENTITY（PG 17 语法）
ALTER TABLE student_vision_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_oral_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_mental_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE weight_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_bone_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
