ALTER TABLE student_vision_record ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_oral_record ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_mental_record ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE weight_record ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_bone_record ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
