ALTER TABLE student_vision_record ALTER COLUMN id DROP DEFAULT;
ALTER TABLE student_oral_record ALTER COLUMN id DROP DEFAULT;
ALTER TABLE student_mental_record ALTER COLUMN id DROP DEFAULT;
ALTER TABLE weight_record ALTER COLUMN id DROP DEFAULT;
ALTER TABLE student_bone_record ALTER COLUMN id DROP DEFAULT;

ALTER TABLE student_vision_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_oral_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_mental_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE weight_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_bone_record ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
