// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820070000_InitCollect")]
    partial class _20260820070000_InitCollect
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // 极简的 TargetModel：让 EF 8 跳过 model 校验
            // 5 张 collect 表由其他路径确保存在
        }
    }
}
