// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817081021_SwitchDataScopeToDigit")]
    partial class SwitchDataScopeToDigit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.SysDict", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("USER");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DictType")
                        .IsUnique();

                    b.ToTable("sys_dict");

                    b.HasData(
                        new
                        {
                            Id = 100L,
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            DictName = "角色数据权限",
                            DictType = "role_based_data_permissions",
                            OwnerType = "SYSTEM",
                            Remark = "角色管理中可分配的数据权限范围（全部/自定义/本部门/本部门及以下/仅本人）",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.SysDictItem", b =>
                {
                    b.Property<string>("DictType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ItemValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DictType", "ItemValue");

                    b.ToTable("sys_dict_item");

                    b.HasData(
                        new
                        {
                            DictType = "role_based_data_permissions",
                            ItemValue = "1",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            ItemLabel = "全部数据权限",
                            Remark = "可访问所有数据",
                            SortOrder = 1,
                            Status = 1
                        },
                        new
                        {
                            DictType = "role_based_data_permissions",
                            ItemValue = "2",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            ItemLabel = "自定义数据权限",
                            Remark = "按指定部门范围访问",
                            SortOrder = 2,
                            Status = 1
                        },
                        new
                        {
                            DictType = "role_based_data_permissions",
                            ItemValue = "3",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            ItemLabel = "本部门数据权限",
                            Remark = "仅访问本部门数据",
                            SortOrder = 3,
                            Status = 1
                        },
                        new
                        {
                            DictType = "role_based_data_permissions",
                            ItemValue = "4",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            ItemLabel = "本部门及以下数据权限",
                            Remark = "可访问本部门及下级部门数据",
                            SortOrder = 4,
                            Status = 1
                        },
                        new
                        {
                            DictType = "role_based_data_permissions",
                            ItemValue = "5",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            ItemLabel = "仅本人数据权限",
                            Remark = "仅能访问自己的数据",
                            SortOrder = 5,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.SysMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Component")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("component");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<int>("IsExternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("is_external");

                    b.Property<int>("IsKeepAlive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("is_keep_alive");

                    b.Property<int>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("path");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("RouteParams")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("route_params");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("sys_menu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "SYSTEM",
                            Icon = "ant-design:settings",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "系统管理",
                            Sort = 1,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "system:user",
                            Component = "vision-archive/system/user/index",
                            Icon = "ant-design:user",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "用户管理",
                            ParentId = 1L,
                            Path = "/vision-system/user",
                            Permission = "system:user:list",
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 3L,
                            Code = "system:role",
                            Component = "vision-archive/system/role/index",
                            Icon = "ant-design:team",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "角色管理",
                            ParentId = 1L,
                            Path = "/vision-system/role",
                            Permission = "system:role:list",
                            Sort = 2,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 4L,
                            Code = "system:menu",
                            Component = "vision-archive/system/menu/index",
                            Icon = "ant-design:menu",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "菜单管理",
                            ParentId = 1L,
                            Path = "/vision-system/menu",
                            Permission = "system:menu:list",
                            Sort = 3,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 5L,
                            Code = "system:org",
                            Component = "vision-archive/system/org/index",
                            Icon = "ant-design:apartment",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "组织管理",
                            ParentId = 1L,
                            Path = "/vision-system/org",
                            Permission = "system:org:list",
                            Sort = 4,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 7L,
                            Code = "system:dict",
                            Component = "vision-archive/system/dict/index",
                            Icon = "ant-design:book",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "字典管理",
                            ParentId = 1L,
                            Path = "/vision-system/dict",
                            Permission = "system:dict:list",
                            Sort = 5,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 10L,
                            Code = "system:log",
                            Component = "vision-archive/system/log/index",
                            Icon = "ant-design:file-text",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "操作日志",
                            ParentId = 1L,
                            Path = "/vision-system/log",
                            Permission = "system:log:list",
                            Sort = 6,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 11L,
                            Code = "MONITOR",
                            Icon = "ant-design:dashboard",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "系统监控",
                            Sort = 2,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 12L,
                            Code = "monitor:online",
                            Component = "monitor/online/index",
                            Icon = "ant-design:user",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "在线用户",
                            ParentId = 11L,
                            Path = "/monitor/online",
                            Permission = "monitor:online:list",
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 13L,
                            Code = "TOOLS",
                            Icon = "ant-design:tool",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "系统工具",
                            Sort = 3,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 14L,
                            Code = "tools:form",
                            Component = "tools/form/index",
                            Icon = "ant-design:form",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "表单构建",
                            ParentId = 13L,
                            Path = "/tools/form",
                            Permission = "tools:form:list",
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 15L,
                            Code = "DATA",
                            Icon = "ant-design:database",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "数据管理",
                            Sort = 4,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 16L,
                            Code = "screen",
                            Component = "screen/index",
                            Icon = "ant-design:global",
                            IsExternal = 0,
                            IsKeepAlive = 1,
                            IsVisible = 1,
                            Name = "大屏管理",
                            ParentId = 15L,
                            Path = "/screen",
                            Permission = "screen:list",
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 100L,
                            Code = "",
                            IsExternal = 0,
                            IsKeepAlive = 0,
                            IsVisible = 1,
                            Name = "用户新增",
                            ParentId = 2L,
                            Permission = "system:user:add",
                            Sort = 1,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 101L,
                            Code = "",
                            IsExternal = 0,
                            IsKeepAlive = 0,
                            IsVisible = 1,
                            Name = "用户修改",
                            ParentId = 2L,
                            Permission = "system:user:edit",
                            Sort = 2,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 102L,
                            Code = "",
                            IsExternal = 0,
                            IsKeepAlive = 0,
                            IsVisible = 1,
                            Name = "用户删除",
                            ParentId = 2L,
                            Permission = "system:user:delete",
                            Sort = 3,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 103L,
                            Code = "",
                            IsExternal = 0,
                            IsKeepAlive = 0,
                            IsVisible = 1,
                            Name = "角色新增",
                            ParentId = 3L,
                            Permission = "system:role:add",
                            Sort = 1,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 104L,
                            Code = "",
                            IsExternal = 0,
                            IsKeepAlive = 0,
                            IsVisible = 1,
                            Name = "角色修改",
                            ParentId = 3L,
                            Permission = "system:role:edit",
                            Sort = 2,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 105L,
                            Code = "",
                            IsExternal = 0,
                            IsKeepAlive = 0,
                            IsVisible = 1,
                            Name = "角色删除",
                            ParentId = 3L,
                            Permission = "system:role:delete",
                            Sort = 3,
                            Status = 1,
                            Type = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.SysOrg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Status");

                    b.ToTable("sys_org", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "GJ-001",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = "国家级",
                            Name = "国家教育部",
                            Sort = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "SJ-001",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 5, 0, 0, DateTimeKind.Local),
                            Level = "省级",
                            Name = "江苏省教育厅",
                            ParentId = 1L,
                            Sort = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "SJ-002",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 10, 0, 0, DateTimeKind.Local),
                            Level = "省级",
                            Name = "浙江省教育厅",
                            ParentId = 1L,
                            Sort = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4L,
                            Code = "SHI-001",
                            CreatedAt = new DateTime(2025, 1, 12, 10, 0, 0, 0, DateTimeKind.Local),
                            Level = "市级",
                            Name = "南京市教育局",
                            ParentId = 2L,
                            Sort = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 5L,
                            Code = "SHI-002",
                            CreatedAt = new DateTime(2025, 1, 12, 10, 5, 0, 0, DateTimeKind.Local),
                            Level = "市级",
                            Name = "苏州市教育局",
                            ParentId = 2L,
                            Sort = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 6L,
                            Code = "QX-001",
                            CreatedAt = new DateTime(2025, 1, 15, 14, 0, 0, 0, DateTimeKind.Local),
                            Level = "区县级",
                            Name = "鼓楼区教育局",
                            ParentId = 4L,
                            Sort = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7L,
                            Code = "XX-001",
                            CreatedAt = new DateTime(2025, 2, 1, 8, 30, 0, 0, DateTimeKind.Local),
                            Level = "学校级",
                            Name = "南京市第一中学",
                            ParentId = 6L,
                            Sort = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8L,
                            Code = "XX-002",
                            CreatedAt = new DateTime(2025, 2, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = "学校级",
                            Name = "南京市金陵中学",
                            ParentId = 6L,
                            Sort = 2,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.SysRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("ALL")
                        .HasColumnName("data_scope");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("sys_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ROLE_NATIONAL",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            DataScope = "1",
                            Level = 1,
                            Name = "国家管理员",
                            Permission = "system:national",
                            Remark = "查看全国所有数据，统一下发标准、生成全国报表，管理省级账号",
                            Status = 1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "ROLE_PROVINCE",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            DataScope = "4",
                            Level = 2,
                            Name = "省级管理员",
                            Permission = "system:province",
                            Remark = "查看本省及各地市数据，生成省级报表、监控地市防控，管理市级账号",
                            Status = 1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "ROLE_CITY",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            DataScope = "4",
                            Level = 3,
                            Name = "市级管理员",
                            Permission = "system:city",
                            Remark = "查看本市及各县区数据，监控数据质量、发布预警，管理县级账号",
                            Status = 1
                        },
                        new
                        {
                            Id = 4L,
                            Code = "ROLE_DISTRICT",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            DataScope = "4",
                            Level = 4,
                            Name = "县级管理员",
                            Permission = "system:district",
                            Remark = "查看本县所有学校数据，审核数据、督导防控工作，管理学校账号",
                            Status = 1
                        },
                        new
                        {
                            Id = 5L,
                            Code = "ROLE_SCHOOL",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            DataScope = "3",
                            Level = 5,
                            Name = "学校管理员",
                            Permission = "system:school",
                            Remark = "仅管理本校数据，录入/审核视力档案，查看本校统计",
                            Status = 1
                        },
                        new
                        {
                            Id = 6L,
                            Code = "ROLE_DOCTOR",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            DataScope = "3",
                            Level = 5,
                            Name = "校医",
                            Permission = "system:doctor",
                            Remark = "录入/审核视力数据，查看本校统计分析",
                            Status = 1
                        },
                        new
                        {
                            Id = 7L,
                            Code = "ROLE_TEACHER",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            DataScope = "5",
                            Level = 5,
                            Name = "班主任",
                            Permission = "system:teacher",
                            Remark = "仅管理本班学生数据，录入视力档案，查看本班统计",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.SysRoleMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique();

                    b.ToTable("sys_role_menu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<long>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("Domain.Entities.SysDictItem", b =>
                {
                    b.HasOne("Domain.Entities.SysDict", "Dict")
                        .WithMany("DictItems")
                        .HasForeignKey("DictType")
                        .HasPrincipalKey("DictType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dict");
                });

            modelBuilder.Entity("Domain.Entities.SysDict", b =>
                {
                    b.Navigation("DictItems");
                });
#pragma warning restore 612, 618
        }
    }
}
