// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728080000_AddSysDict")]
    partial class AddSysDict
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.SysDict", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DictType")
                        .IsUnique();

                    b.ToTable("sys_dict");
                });

            // 保留 sys_user 的旧映射
            modelBuilder.Entity("Domain.Entities.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email").IsRequired().HasColumnType("text");
                    b.Property<int>("Gender").HasColumnType("integer");
                    b.Property<long>("OrgId").HasColumnType("bigint");
                    b.Property<string>("PasswordHash").HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string>("PhoneNumber").IsRequired().HasColumnType("text");
                    b.Property<string>("RealName").IsRequired().HasColumnType("text");
                    b.Property<long>("RoleId").HasColumnType("bigint");
                    b.Property<int>("Status").HasColumnType("integer");
                    b.Property<string>("Username").IsRequired().HasColumnType("text");

                    b.HasKey("Id");
                    b.ToTable("sys_user");
                });
#pragma warning restore 612, 618
        }
    }
}
