// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.SysDict", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("USER");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DictType")
                        .IsUnique();

                    b.ToTable("sys_dict");
                });

            modelBuilder.Entity("Domain.Entities.SysDictItem", b =>
                {
                    b.Property<string>("DictType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ItemValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DictType", "ItemValue");

                    b.ToTable("sys_dict_item");
                });

            modelBuilder.Entity("Domain.Entities.SysMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Component")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("component");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Icon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("path");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasColumnName("sort");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("sys_menu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "DATA_VIEW",
                            Icon = "📊",
                            Name = "数据查看权限",
                            Sort = 1,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 7L,
                            Code = "DATA_OPERATE",
                            Icon = "📝",
                            Name = "数据操作权限",
                            Sort = 2,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 13L,
                            Code = "REPORT",
                            Icon = "📋",
                            Name = "报表权限",
                            Sort = 3,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 16L,
                            Code = "ALERT",
                            Icon = "🔔",
                            Name = "预警权限",
                            Sort = 4,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 19L,
                            Code = "SYSTEM",
                            Icon = "⚙️",
                            Name = "系统管理权限",
                            Sort = 5,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "VIEW_NATIONAL",
                            Name = "查看全国数据",
                            ParentId = 1L,
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 3L,
                            Code = "VIEW_PROVINCE",
                            Name = "查看省级数据",
                            ParentId = 1L,
                            Sort = 2,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 4L,
                            Code = "VIEW_CITY",
                            Name = "查看市级数据",
                            ParentId = 1L,
                            Sort = 3,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 5L,
                            Code = "VIEW_DISTRICT",
                            Name = "查看县级数据",
                            ParentId = 1L,
                            Sort = 4,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 6L,
                            Code = "VIEW_SCHOOL",
                            Name = "查看校级数据",
                            ParentId = 1L,
                            Sort = 5,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 8L,
                            Code = "DATA_ADD",
                            Name = "新增数据",
                            ParentId = 7L,
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 9L,
                            Code = "DATA_EDIT",
                            Name = "编辑数据",
                            ParentId = 7L,
                            Sort = 2,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 10L,
                            Code = "DATA_DELETE",
                            Name = "删除数据",
                            ParentId = 7L,
                            Sort = 3,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 11L,
                            Code = "DATA_AUDIT",
                            Name = "审核数据",
                            ParentId = 7L,
                            Sort = 4,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 12L,
                            Code = "DATA_IMPORT_EXPORT",
                            Name = "导入导出",
                            ParentId = 7L,
                            Sort = 5,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 14L,
                            Code = "REPORT_GENERATE",
                            Name = "生成报表",
                            ParentId = 13L,
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 15L,
                            Code = "REPORT_EXPORT",
                            Name = "导出报表",
                            ParentId = 13L,
                            Sort = 2,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 17L,
                            Code = "ALERT_VIEW",
                            Name = "查看预警",
                            ParentId = 16L,
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 18L,
                            Code = "ALERT_PUBLISH",
                            Name = "发布预警",
                            ParentId = 16L,
                            Sort = 2,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 20L,
                            Code = "SYS_USER",
                            Name = "用户管理",
                            ParentId = 19L,
                            Sort = 1,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 21L,
                            Code = "SYS_ROLE",
                            Name = "角色管理",
                            ParentId = 19L,
                            Sort = 2,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 22L,
                            Code = "SYS_ORG",
                            Name = "组织管理",
                            ParentId = 19L,
                            Sort = 3,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 23L,
                            Code = "SYS_DICT",
                            Name = "字典管理",
                            ParentId = 19L,
                            Sort = 4,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 24L,
                            Code = "SYS_LOG",
                            Name = "日志查看",
                            ParentId = 19L,
                            Sort = 5,
                            Status = 1,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.SysOrg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Status");

                    b.ToTable("sys_org", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "GJ-001",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = "国家级",
                            Name = "国家教育部",
                            Sort = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "SJ-001",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 5, 0, 0, DateTimeKind.Local),
                            Level = "省级",
                            Name = "江苏省教育厅",
                            ParentId = 1L,
                            Sort = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "SJ-002",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 10, 0, 0, DateTimeKind.Local),
                            Level = "省级",
                            Name = "浙江省教育厅",
                            ParentId = 1L,
                            Sort = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4L,
                            Code = "SHI-001",
                            CreatedAt = new DateTime(2025, 1, 12, 10, 0, 0, 0, DateTimeKind.Local),
                            Level = "市级",
                            Name = "南京市教育局",
                            ParentId = 2L,
                            Sort = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 5L,
                            Code = "SHI-002",
                            CreatedAt = new DateTime(2025, 1, 12, 10, 5, 0, 0, DateTimeKind.Local),
                            Level = "市级",
                            Name = "苏州市教育局",
                            ParentId = 2L,
                            Sort = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 6L,
                            Code = "QX-001",
                            CreatedAt = new DateTime(2025, 1, 15, 14, 0, 0, 0, DateTimeKind.Local),
                            Level = "区县级",
                            Name = "鼓楼区教育局",
                            ParentId = 4L,
                            Sort = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7L,
                            Code = "XX-001",
                            CreatedAt = new DateTime(2025, 2, 1, 8, 30, 0, 0, DateTimeKind.Local),
                            Level = "学校级",
                            Name = "南京市第一中学",
                            ParentId = 6L,
                            Sort = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8L,
                            Code = "XX-002",
                            CreatedAt = new DateTime(2025, 2, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = "学校级",
                            Name = "南京市金陵中学",
                            ParentId = 6L,
                            Sort = 2,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.SysRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("sys_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ROLE_NATIONAL",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = 1,
                            Name = "国家管理员",
                            Remark = "查看全国所有数据，统一下发标准、生成全国报表，管理省级账号",
                            Status = 1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "ROLE_PROVINCE",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = 2,
                            Name = "省级管理员",
                            Remark = "查看本省及各地市数据，生成省级报表、监控地市防控，管理市级账号",
                            Status = 1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "ROLE_CITY",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = 3,
                            Name = "市级管理员",
                            Remark = "查看本市及各县区数据，监控数据质量、发布预警，管理县级账号",
                            Status = 1
                        },
                        new
                        {
                            Id = 4L,
                            Code = "ROLE_DISTRICT",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = 4,
                            Name = "县级管理员",
                            Remark = "查看本县所有学校数据，审核数据、督导防控工作，管理学校账号",
                            Status = 1
                        },
                        new
                        {
                            Id = 5L,
                            Code = "ROLE_SCHOOL",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = 5,
                            Name = "学校管理员",
                            Remark = "仅管理本校数据，录入/审核视力档案，查看本校统计",
                            Status = 1
                        },
                        new
                        {
                            Id = 6L,
                            Code = "ROLE_DOCTOR",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = 5,
                            Name = "校医",
                            Remark = "录入/审核视力数据，查看本校统计分析",
                            Status = 1
                        },
                        new
                        {
                            Id = 7L,
                            Code = "ROLE_TEACHER",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Local),
                            Level = 5,
                            Name = "班主任",
                            Remark = "仅管理本班学生数据，录入视力档案，查看本班统计",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.SysRoleMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique();

                    b.ToTable("sys_role_menu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<long>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("Domain.Entities.SysDictItem", b =>
                {
                    b.HasOne("Domain.Entities.SysDict", "Dict")
                        .WithMany("DictItems")
                        .HasForeignKey("DictType")
                        .HasPrincipalKey("DictType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dict");
                });

            modelBuilder.Entity("Domain.Entities.SysDict", b =>
                {
                    b.Navigation("DictItems");
                });
#pragma warning restore 612, 618
        }
    }
}
