-- Create sys_role table
CREATE TABLE IF NOT EXISTS sys_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    code varchar(50) NOT NULL,
    level integer NOT NULL,
    status integer NOT NULL DEFAULT 1,
    remark varchar(500),
    created_at timestamptz DEFAULT NOW(),
    updated_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS IX_sys_role_code ON sys_role (code);

-- Seed roles
INSERT INTO sys_role (id, name, code, level, status, remark, created_at) VALUES
(1, '国家管理员', 'ROLE_NATIONAL', 1, 1, '查看全国所有数据，统一下发标准、生成全国报表，管理省级账号', '2025-01-10 09:00:00+08'),
(2, '省级管理员', 'ROLE_PROVINCE', 2, 1, '查看本省及各地市数据，生成省级报表、监控地市防控，管理市级账号', '2025-01-10 09:00:00+08'),
(3, '市级管理员', 'ROLE_CITY', 3, 1, '查看本市及各县区数据，监控数据质量、发布预警，管理县级账号', '2025-01-10 09:00:00+08'),
(4, '县级管理员', 'ROLE_DISTRICT', 4, 1, '查看本县所有学校数据，审核数据、督导防控工作，管理学校账号', '2025-01-10 09:00:00+08'),
(5, '学校管理员', 'ROLE_SCHOOL', 5, 1, '仅管理本校数据，录入/审核视力档案，查看本校统计', '2025-01-10 09:00:00+08'),
(6, '校医', 'ROLE_DOCTOR', 5, 1, '录入/审核视力数据，查看本校统计分析', '2025-01-10 09:00:00+08'),
(7, '班主任', 'ROLE_TEACHER', 5, 1, '仅管理本班学生数据，录入视力档案，查看本班统计', '2025-01-10 09:00:00+08')
ON CONFLICT (id) DO NOTHING;

-- Create sys_menu table
CREATE TABLE IF NOT EXISTS sys_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    code varchar(50),
    icon varchar(20),
    type integer NOT NULL,
    parent_id bigint,
    sort integer NOT NULL DEFAULT 0,
    status integer NOT NULL DEFAULT 1,
    path varchar(200),
    component varchar(200),
    created_at timestamptz DEFAULT NOW(),
    updated_at timestamptz
);

INSERT INTO sys_menu (id, name, code, icon, type, parent_id, sort, status) VALUES
(1, '数据查看权限', 'DATA_VIEW', '📊', 1, NULL, 1, 1),
(2, '查看全国数据', 'VIEW_NATIONAL', NULL, 2, 1, 1, 1),
(3, '查看省级数据', 'VIEW_PROVINCE', NULL, 2, 1, 2, 1),
(4, '查看市级数据', 'VIEW_CITY', NULL, 2, 1, 3, 1),
(5, '查看县级数据', 'VIEW_DISTRICT', NULL, 2, 1, 4, 1),
(6, '查看校级数据', 'VIEW_SCHOOL', NULL, 2, 1, 5, 1),
(7, '数据操作权限', 'DATA_OPERATE', '📝', 1, NULL, 2, 1),
(8, '新增数据', 'DATA_ADD', NULL, 2, 7, 1, 1),
(9, '编辑数据', 'DATA_EDIT', NULL, 2, 7, 2, 1),
(10, '删除数据', 'DATA_DELETE', NULL, 2, 7, 3, 1),
(11, '审核数据', 'DATA_AUDIT', NULL, 2, 7, 4, 1),
(12, '导入导出', 'DATA_IMPORT_EXPORT', NULL, 2, 7, 5, 1),
(13, '报表权限', 'REPORT', '📋', 1, NULL, 3, 1),
(14, '生成报表', 'REPORT_GENERATE', NULL, 2, 13, 1, 1),
(15, '导出报表', 'REPORT_EXPORT', NULL, 2, 13, 2, 1),
(16, '预警权限', 'ALERT', '🔔', 1, NULL, 4, 1),
(17, '查看预警', 'ALERT_VIEW', NULL, 2, 16, 1, 1),
(18, '发布预警', 'ALERT_PUBLISH', NULL, 2, 16, 2, 1),
(19, '系统管理权限', 'SYSTEM', '⚙️', 1, NULL, 5, 1),
(20, '用户管理', 'SYS_USER', NULL, 2, 19, 1, 1),
(21, '角色管理', 'SYS_ROLE', NULL, 2, 19, 2, 1),
(22, '组织管理', 'SYS_ORG', NULL, 2, 19, 3, 1),
(23, '字典管理', 'SYS_DICT', NULL, 2, 19, 4, 1),
(24, '日志查看', 'SYS_LOG', NULL, 2, 19, 5, 1)
ON CONFLICT (id) DO NOTHING;

-- Create sys_role_menu table
CREATE TABLE IF NOT EXISTS sys_role_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    created_at timestamptz DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS IX_sys_role_menu_role_id_menu_id ON sys_role_menu (role_id, menu_id);
CREATE INDEX IF NOT EXISTS IX_sys_role_menu_role_id ON sys_role_menu (role_id);
CREATE INDEX IF NOT EXISTS IX_sys_role_menu_menu_id ON sys_role_menu (menu_id);

-- Register migration
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260729160000_AddRoleMenuTables', '9.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;
